name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout do código do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Configurar o AWS CLI (se necessário, caso precise interagir com AWS)
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Ajuste para a região da instância EC2

      # Step 3: Configurar o SSH para conectar à instância EC2
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      # Step 4: Atualizar o repositório na instância EC2
      - name: Update repository on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
            cd /caminho/para/diretorio/servido/pelo/container
            git pull origin main
            # Se necessário, reinicie o contêiner Docker
            docker ps -q --filter "name=apache-php-container" | grep -q . && docker restart apache-php-container || echo "Container não encontrado, verifique o nome do contêiner."
          EOF
